version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: financial-planner
        uid: 1000
    container_name: financial-planner-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - financial-planner
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: financial_planners
      DB_USERNAME: root
      DB_PASSWORD: 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: financial-planner-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 
      PMA_USER: root
      PMA_PASSWORD: 
    networks:
      - financial-planner
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: financial-planner-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - financial-planner
    depends_on:
      - app

networks:
  financial-planner:
    driver: bridge

volumes:
  dbdata:
    driver: local 